CREATE TABLE regions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);

INSERT INTO regions (name)
VALUES
    ('Highlands'),
    ('Lowlands'),
    ('Islay'),
    ('Campbeltown'),
    ('Speyside'),
    ('Island');

CREATE TABLE distilleries (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    region_id INT REFERENCES regions(id)
);

CREATE TABLE type (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);

INSERT INTO type (name)
VALUES
    ('Single malt'),
    ('Single grain'),
    ('Blended malt'),
    ('Blended');

CREATE TABLE countries (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);

INSERT INTO countries (name) VALUES ('Scotch');

CREATE TABLE whiskies (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distillery_id INT NOT NULL REFERENCES distilleries(id),
    type_id INT NOT NULL REFERENCES type(id),
    country_id INT NOT NULL REFERENCES countries(id),
    age INT
);
