CREATE TABLE reviewers
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE tasting_types
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR NOT NULL
);

INSERT INTO tasting_types (type)
VALUES ('Bottle'),
       ('Miniature'),
       ('Whisky Tasting Tour'),
       ('Bar');

CREATE TABLE reviews
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    whisky_id       INT  NOT NULL REFERENCES whiskies (id),
    reviewer_id     INT  NOT NULL REFERENCES reviewers (id),
    tasting_type_id INT REFERENCES tasting_types (id),
    score           INT  NOT NULL,
    CONSTRAINT positive_score CHECK (score > 0),
    CONSTRAINT maximum_score_five CHECK (score <= 5),
    comment         VARCHAR,
    date            DATE NOT NULL
);
